apiVersion: v1
kind: Service
metadata:
  name: cv-website
  namespace: cv
  labels:
    app: cv-website
    cilium.io/lb-pool: pool-2
    cilium.io/bgp-advertise: "true"
spec:
  type: LoadBalancer
  selector:
    app: cv-website
  ports:
    - name: http
      port: 80
      targetPort: http
